import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Farm modules tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon_logo-1.jpg" /> {/* Update the path to your icon */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
